# _config.yml 关键配置示例

# 你 GitHub Pages 的地址
url: "https://Cx330yyy.github.io"  

# 仓库名作为 baseurl，注意前面有 /，末尾没有 /
baseurl: "/Cx330yyy.github.io"  

# 其他常用配置保持原样
title: "你的博客标题"
description: "你的博客描述"
theme: jekyll-theme-chirpy
author: 
  name: "你的名字"

